apiVersion: v1
kind: Pod
metadata:
  name: music-player-pod
  labels:
    app: music-player
spec:
  containers:
    - name: music-player-ctr
      image: raniingale2025/music_player:v1
      ports:
        - containerPort: 3000
      env:
        - name: DB_HOST
          value: "mysql"
        - name: DB_USER
          value: "root"
        - name: DB_PASS
          value: "rootpassword"
        - name: DB_NAME
          value: "music_player"
      imagePullPolicy: Always
