apiVersion: v1
kind: Service
metadata:
  name: music-player-service

spec:
  selector:
    app: music-player

  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 30007
  type: NodePort

